# Generated by Django 5.1.15 on 2026-05-16 20:10

import apps.accounts.managers
import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(default=apps.accounts.models._default_user_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('role', models.CharField(choices=[('student', 'Élève'), ('parent', 'Parent'), ('counselor', 'Conseiller'), ('school_admin', 'Administrateur école partenaire'), ('path_admin', 'Administrateur Path-Advisor')], default='student', max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('email_unverified', 'Email non vérifié'), ('pending_parental_consent', 'Consentement parental en attente'), ('active', 'Actif'), ('suspended', 'Suspendu'), ('deleted', 'Supprimé')], default='email_unverified', max_length=30)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('consent_rgpd_at', models.DateTimeField(blank=True, null=True)),
                ('consent_cgu_version', models.CharField(blank=True, max_length=20, null=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['status'], name='users_status_9ca66f_idx'), models.Index(fields=['role'], name='users_role_0ace22_idx')],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
