# Generated by Django 5.1.15 on 2026-05-17 15:20

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_default_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentalConsent',
            fields=[
                ('id', models.CharField(default=apps.accounts.models._default_parental_consent_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_user_id', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=apps.accounts.models._default_parental_consent_expires_at)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, choices=[('granted', 'Autorisé'), ('refused', 'Refusé')], max_length=10, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('decision_ip_truncated', models.CharField(blank=True, max_length=45, null=True)),
                ('decision_user_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parental_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parental_consents',
                'indexes': [models.Index(fields=['decision', 'requested_at'], name='parental_co_decisio_f8bf9d_idx'), models.Index(fields=['decision', 'expires_at'], name='parental_co_decisio_59c09c_idx'), models.Index(fields=['student', 'decision'], name='parental_co_student_9fc2c4_idx')],
            },
        ),
    ]
