# Generated by Django 5.1.15 on 2026-05-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_parentalconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentalconsent',
            name='client_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentalconsent',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
