# Generated by Django 5.1.15 on 2026-05-24 12:36

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Story 1.8 RLS migration `0007_enable_rls` shipped concurrently;
        # chain after it so the AccountDeletionRequest table is created in a
        # schema that already has the RLS policies + tenant context plumbing.
        ('accounts', '0007_enable_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.CharField(default=apps.accounts.models._default_account_deletion_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('user_id_snapshot', models.CharField(db_index=True, max_length=32)),
                ('cancel_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('hard_delete_after', models.DateTimeField(default=apps.accounts.models._default_account_deletion_hard_delete_after)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('hard_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hard_delete_attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('last_failure_code', models.CharField(blank=True, max_length=50, null=True)),
                ('requested_ip_truncated', models.CharField(blank=True, max_length=45, null=True)),
                ('requested_user_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('password_hash_at_request', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_deletion_requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['hard_delete_after', 'cancelled_at', 'hard_deleted_at'], name='idx_acct_del_sweep'), models.Index(fields=['user_id_snapshot', '-requested_at'], name='idx_acct_del_user_req')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True), ('hard_deleted_at__isnull', True)), fields=('user_id_snapshot',), name='uniq_acct_del_active_per_user')],
            },
        ),
    ]
