# Generated by Django 5.1.15 on 2026-05-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_deletion_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountdeletionrequest',
            options={'ordering': ['-requested_at'], 'permissions': [('cancel_deletion_request', 'Can cancel an in-flight account-deletion request (DPO)')]},
        ),
    ]
