# Generated by Django 5.1.15 on 2026-05-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_deletion_dpo_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
