# Generated by Django 5.1.15 on 2026-05-30 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_locked_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='MfaProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mfa_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('enrolled_at', models.DateTimeField(blank=True, help_text='Set on successful `mfa.confirm_enrollment` — the moment the user first verified a TOTP code. Reset to NULL by DPO override.', null=True)),
                ('last_challenge_at', models.DateTimeField(blank=True, help_text="Updated on every successful `mfa.verify_challenge`. Used by `recovery-codes/regenerate/` to enforce 'recent challenge' re-auth (cf. Story 1.6 §T5).", null=True)),
                ('requires_enrollment_at_next_login', models.BooleanField(default=False, help_text='Set to TRUE by `mfa.reset_by_dpo` (Story 1.6 §AC7). The next login forces the user through enrollment again, even though their `role` would normally only force enrollment on the very first login. Cleared on the next successful enrollment-confirm.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MFA profile',
                'verbose_name_plural': 'MFA profiles',
                'db_table': 'accounts_mfa_profile',
            },
        ),
    ]
