# Generated by Django 5.1.15 on 2026-06-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_mfa_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Élève'), ('parent', 'Parent'), ('counselor', 'Conseiller'), ('school_admin', 'Administrateur école partenaire'), ('path_admin', 'Administrateur Path-Advisor'), ('support', 'Support utilisateur')], default='student', max_length=20),
        ),
    ]
