/**
 * Thin fetch wrapper for the Django REST API.
 *
 * Story 1.1 seed: minimal surface — base URL + JSON helpers + CSRF header pass-through.
 * Story 1.5 will add session-cookie handling, RFC 7807 error parsing, and a typed client
 * built on top of `src/lib/api/generated/schema.ts` (auto-generated by `make openapi`).
 *
 * Rule (cf. story §4.4): no component should call `fetch` directly — everything goes
 * through this module.
 */

// Two URLs because Server Components run inside the `web` container and must reach
// the API via the Docker network (http://api:8000), while Client Components run in
// the user's browser and need a host-reachable URL (http://localhost:8000 in dev).
const API_BASE_URL =
  typeof window === "undefined"
    ? (process.env.API_URL_SERVER ?? "http://api:8000")
    : (process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000");

export interface ApiRequestInit extends Omit<RequestInit, "body"> {
  body?: unknown;
  csrfToken?: string;
}

export async function apiFetch<T>(path: string, init: ApiRequestInit = {}): Promise<T> {
  const { body, csrfToken, headers, ...rest } = init;
  const url = `${API_BASE_URL}${path.startsWith("/") ? path : `/${path}`}`;

  const response = await fetch(url, {
    ...rest,
    credentials: "include",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
      ...(csrfToken ? { "X-CSRFToken": csrfToken } : {}),
      ...headers,
    },
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });

  if (!response.ok) {
    // Story 1.5 will parse RFC 7807 Problem Details here.
    throw new Error(`API ${response.status} ${response.statusText}`);
  }

  if (response.status === 204) {
    return undefined as T;
  }

  return (await response.json()) as T;
}
