# Generated by Django 5.1.15 on 2026-06-21 10:32
#
# The two `RemoveIndex` ops were neutralized post-hoc (2026-08): migration
# 0002 no longer adds `professions_signals_json_gin` /
# `professions_level_compat_gin` (it was itself neutralized — GinIndex broke
# the SQLite fast test lane), so removing indexes that no longer exist in
# migration state would raise. Net effect on any already-migrated
# environment is unchanged — those indexes are gone either way.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("professions", "0003_profession_report"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="profession",
            new_name="professions_is_acti_8d5010_idx",
            old_name="professions_is_acti_sector_idx",
        ),
    ]
