# Generated by Django 5.1.15 on 2026-06-21 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("professions", "0003_profession_report"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="profession",
            name="professions_signals_json_gin",
        ),
        migrations.RemoveIndex(
            model_name="profession",
            name="professions_level_compat_gin",
        ),
        migrations.RenameIndex(
            model_name="profession",
            new_name="professions_is_acti_8d5010_idx",
            old_name="professions_is_acti_sector_idx",
        ),
    ]
