# Generated by Django 5.1.15 on 2026-09-26 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.professions.models


class Migration(migrations.Migration):
    dependencies = [
        ("professions", "0005_level_compatibility_jsonfield"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profession",
            name="status",
            field=models.CharField(
                choices=[("draft", "Brouillon"), ("published", "Publié"), ("archived", "Archivé")],
                db_index=True,
                default="published",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="ProfessionRevision",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.professions.models._default_revision_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("snapshot", models.JSONField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Création"),
                            ("updated", "Modification"),
                            ("status_changed", "Changement de statut"),
                            ("rolled_back", "Rollback"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="professions.profession",
                    ),
                ),
                (
                    "restored_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="professions.professionrevision",
                    ),
                ),
            ],
            options={
                "db_table": "profession_revisions",
                "ordering": ["-created_at"],
            },
        ),
    ]
