# Generated by Django 5.1.15 on 2026-09-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professions", "0008_professionreport_admin_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professionreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("resolved", "Résolu"),
                    ("dismissed", "Rejeté"),
                    ("info_requested", "Précisions demandées"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
