# Generated by Django 5.1.15 on 2026-09-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("establishments", "0003_enable_rls_invitations_and_jobs"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cohort",
            constraint=models.UniqueConstraint(
                fields=("establishment", "name", "school_year"),
                name="unique_cohort_per_establishment_name_year",
            ),
        ),
    ]
