# Generated by Django 5.1.15 on 2026-09-06 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.establishments.models


class Migration(migrations.Migration):
    dependencies = [
        ("establishments", "0005_counselorconsent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CounselorNote",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.establishments.models._default_counselor_note_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "counselor_notes",
                "ordering": ["-created_at"],
            },
        ),
    ]
