# Generated by Django 5.1.15 on 2026-09-27 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.establishments.models


class Migration(migrations.Migration):
    dependencies = [
        ("establishments", "0006_counselornote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CounselorIntervention",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.establishments.models._default_counselor_intervention_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "counselor_interventions",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("counselor", "student"),
                        name="unique_intervention_per_student_counselor",
                    )
                ],
            },
        ),
    ]
