"""Management command to seed the schools & formations referential — Story 4.1 / 4.7.

Seeds 100+ French educational institutions covering:
- 15+ lycées professionnels
- BTS / BUT / IUT programs
- Grandes écoles (ingénieurs, commerce, santé)
- Universités

Story 4.7: Also seeds Parcours entries (4+ bac pro, 2+ terminale_generale).
"""

from __future__ import annotations

from django.core.management.base import BaseCommand
from django.db import transaction

from apps.schools.models import Formation, Parcours, School

# ---------------------------------------------------------------------------
# Seed data — 100+ établissements
# ---------------------------------------------------------------------------

SCHOOLS_DATA = [
    # ── Lycées professionnels ──────────────────────────────────────────────
    {
        "slug": "lycee-pro-jean-moulin-paris",
        "name": "Lycée Professionnel Jean Moulin",
        "type": School.Type.LYCEE_PRO,
        "city": "Paris",
        "region": "Île-de-France",
        "postal_code": "75013",
        "lat": "48.831400",
        "lon": "2.362200",
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 5,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Lycée professionnel public proposant des bacs pro dans les métiers du commerce, de la vente et des services.",
        "top_debouches": ["Vendeur", "Commercial", "Gestionnaire administratif"],
        "official_url": "https://lycee-jean-moulin-paris.fr",
    },
    {
        "slug": "lycee-pro-gutenberg-croissy",
        "name": "Lycée Professionnel Gutenberg",
        "type": School.Type.LYCEE_PRO,
        "city": "Croissy-Beaubourg",
        "region": "Île-de-France",
        "postal_code": "77183",
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 5,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Bac pro et CAP dans les métiers de la logistique, de l'imprimerie et des métiers de la communication graphique.",
        "top_debouches": ["Technicien logistique", "Conducteur de machines", "Imprimeur"],
        "official_url": "",
    },
    {
        "slug": "lycee-pro-voillaume-aubervilliers",
        "name": "Lycée Professionnel Voillaume",
        "type": School.Type.LYCEE_PRO,
        "city": "Aubervilliers",
        "region": "Île-de-France",
        "postal_code": "93300",
        "apprenticeship": False,
        "internship": True,
        "selectivity_index": 5,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Formation aux métiers de la santé, du médico-social et de la petite enfance.",
        "top_debouches": ["Aide-soignant", "Accompagnant éducatif", "Auxiliaire de puériculture"],
        "official_url": "",
    },
    {
        "slug": "lycee-pro-nicolas-appert-orvault",
        "name": "Lycée Professionnel Nicolas Appert",
        "type": School.Type.LYCEE_PRO,
        "city": "Orvault",
        "region": "Pays de la Loire",
        "postal_code": "44700",
        "lat": "47.268900",
        "lon": "-1.640000",
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 5,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Spécialisé dans les métiers de l'alimentation, de la cuisine et de la restauration.",
        "top_debouches": ["Cuisinier", "Pâtissier", "Responsable de production alimentaire"],
        "official_url": "",
    },
    {
        "slug": "lycee-pro-leonard-de-vinci-melun",
        "name": "Lycée Professionnel Léonard de Vinci",
        "type": School.Type.LYCEE_PRO,
        "city": "Melun",
        "region": "Île-de-France",
        "postal_code": "77000",
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 5,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Formations aux métiers du bâtiment, de l'électrotechnique et de la maintenance industrielle.",
        "top_debouches": ["Électricien", "Technicien de maintenance", "Plombier"],
        "official_url": "",
    },
    {
        "slug": "lycee-pro-jules-verne-nantes",
        "name": "Lycée Professionnel Jules Verne",
        "type": School.Type.LYCEE_PRO,
        "city": "Nantes",
        "region": "Pays de la Loire",
        "postal_code": "44300",
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 5,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Bac pro industries graphiques, commerce et logistique.",
        "top_debouches": ["Technicien imprimerie", "Opérateur logistique", "Commercial"],
        "official_url": "",
    },
    {
        "slug": "lycee-pro-marie-curie-versailles",
        "name": "Lycée Professionnel Marie Curie",
        "type": School.Type.LYCEE_PRO,
        "city": "Versailles",
        "region": "Île-de-France",
        "postal_code": "78000",
        "apprenticeship": False,
        "internship": True,
        "selectivity_index": 5,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Bac pro gestion-administration, métiers de la relation client, systèmes numériques.",
        "top_debouches": ["Gestionnaire RH", "Conseiller clientèle", "Technicien réseaux"],
        "official_url": "",
    },
    {
        "slug": "lycee-pro-pablo-picasso-fontenay",
        "name": "Lycée Professionnel Pablo Picasso",
        "type": School.Type.LYCEE_PRO,
        "city": "Fontenay-sous-Bois",
        "region": "Île-de-France",
        "postal_code": "94120",
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 5,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Formation aux métiers de la mode, du design, de la coiffure et de l'esthétique.",
        "top_debouches": ["Coiffeur", "Esthéticien", "Designer mode"],
        "official_url": "",
    },
    {
        "slug": "lycee-pro-victor-hugo-lyon",
        "name": "Lycée Professionnel Victor Hugo",
        "type": School.Type.LYCEE_PRO,
        "city": "Lyon",
        "region": "Auvergne-Rhône-Alpes",
        "postal_code": "69007",
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 5,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Bac pro métiers de l'accueil, du tourisme et de l'hôtellerie.",
        "top_debouches": ["Réceptionniste", "Agent de voyage", "Hôtelier"],
        "official_url": "",
    },
    {
        "slug": "lycee-pro-antoine-bourdelle-montauban",
        "name": "Lycée Professionnel Antoine Bourdelle",
        "type": School.Type.LYCEE_PRO,
        "city": "Montauban",
        "region": "Occitanie",
        "postal_code": "82000",
        "apprenticeship": False,
        "internship": True,
        "selectivity_index": 5,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Bac pro métiers du bois, de la construction et du génie civil.",
        "top_debouches": ["Charpentier", "Menuisier", "Conducteur de travaux"],
        "official_url": "",
    },
    {
        "slug": "lycee-pro-saint-exupery-marseille",
        "name": "Lycée Professionnel Saint-Exupéry",
        "type": School.Type.LYCEE_PRO,
        "city": "Marseille",
        "region": "Provence-Alpes-Côte d'Azur",
        "postal_code": "13010",
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 5,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Bac pro métiers de la mécanique auto, de l'aéronautique et des systèmes de transport.",
        "top_debouches": ["Mécanicien auto", "Technicien aéronautique", "Carrossier"],
        "official_url": "",
    },
    {
        "slug": "lycee-pro-emile-zola-rennes",
        "name": "Lycée Professionnel Émile Zola",
        "type": School.Type.LYCEE_PRO,
        "city": "Rennes",
        "region": "Bretagne",
        "postal_code": "35000",
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 5,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Formations aux métiers de l'agriculture, de l'agroalimentaire et de l'environnement.",
        "top_debouches": ["Agent agricole", "Technicien agroalimentaire", "Jardinier paysagiste"],
        "official_url": "",
    },
    {
        "slug": "lycee-pro-aristide-briand-gap",
        "name": "Lycée Professionnel Aristide Briand",
        "type": School.Type.LYCEE_PRO,
        "city": "Gap",
        "region": "Provence-Alpes-Côte d'Azur",
        "postal_code": "05000",
        "apprenticeship": False,
        "internship": True,
        "selectivity_index": 5,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Bac pro vente, gestion-administration et métiers de la mode.",
        "top_debouches": ["Vendeur", "Gestionnaire", "Styliste"],
        "official_url": "",
    },
    {
        "slug": "lycee-pro-jean-zay-paris",
        "name": "Lycée Professionnel Jean Zay",
        "type": School.Type.LYCEE_PRO,
        "city": "Paris",
        "region": "Île-de-France",
        "postal_code": "75019",
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 5,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Bac pro systèmes numériques, maintenance et électrotechnique.",
        "top_debouches": ["Technicien réseau", "Électronicien", "Agent de maintenance"],
        "official_url": "",
    },
    {
        "slug": "lycee-pro-camille-claudel-pontault",
        "name": "Lycée Professionnel Camille Claudel",
        "type": School.Type.LYCEE_PRO,
        "city": "Pontault-Combault",
        "region": "Île-de-France",
        "postal_code": "77340",
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 5,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Bac pro métiers de la chimie, plasturgie et procédés industriels.",
        "top_debouches": ["Technicien chimiste", "Plasturgiste", "Opérateur de production"],
        "official_url": "",
    },
    # ── BTS ────────────────────────────────────────────────────────────────
    {
        "slug": "bts-sud-paris-crreteil",
        "name": "BTS Sud Paris - Créteil",
        "type": School.Type.BTS,
        "city": "Créteil",
        "region": "Île-de-France",
        "postal_code": "94000",
        "lat": "48.773000",
        "lon": "2.462200",
        "tuition_min_eur": 0,
        "tuition_max_eur": 300,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 4,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Centre de formation proposant BTS MCO, NDRC, Informatique de gestion et Comptabilité-Gestion.",
        "top_debouches": ["Comptable", "Commercial", "Développeur web"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "",
    },
    {
        "slug": "bts-esiee-paris-noisy",
        "name": "BTS ESIEE Paris - Noisy",
        "type": School.Type.BTS,
        "city": "Noisy-le-Grand",
        "region": "Île-de-France",
        "postal_code": "93160",
        "tuition_min_eur": 0,
        "tuition_max_eur": 300,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 3,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "BTS Systèmes Numériques, BTS Électrotechnique, BTS Conception de Produits Industriels.",
        "top_debouches": [
            "Technicien électronique",
            "Technicien systèmes",
            "Concepteur industriel",
        ],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "",
    },
    {
        "slug": "bts-service-num-bordeaux",
        "name": "BTS Services Numériques Bordeaux",
        "type": School.Type.BTS,
        "city": "Bordeaux",
        "region": "Nouvelle-Aquitaine",
        "postal_code": "33000",
        "tuition_min_eur": 0,
        "tuition_max_eur": 200,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 4,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "BTS Services Informatiques aux Organisations (SIO), option SLAM et SISR.",
        "top_debouches": ["Développeur", "Administrateur réseaux", "Support informatique"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "",
    },
    {
        "slug": "bts-communication-lyon",
        "name": "BTS Communication Lyon",
        "type": School.Type.BTS,
        "city": "Lyon",
        "region": "Auvergne-Rhône-Alpes",
        "postal_code": "69002",
        "tuition_min_eur": 0,
        "tuition_max_eur": 300,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 3,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "BTS Communication, spécialisé dans la création de contenus, la stratégie de marque et le marketing.",
        "top_debouches": ["Chargé de communication", "Community manager", "Chef de projet"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "",
    },
    {
        "slug": "bts-dietetique-nantes",
        "name": "BTS Diététique Nantes",
        "type": School.Type.BTS,
        "city": "Nantes",
        "region": "Pays de la Loire",
        "postal_code": "44000",
        "tuition_min_eur": 0,
        "tuition_max_eur": 250,
        "apprenticeship": False,
        "internship": True,
        "selectivity_index": 3,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "BTS Diététique pour former des professionnels de la nutrition et de la santé alimentaire.",
        "top_debouches": [
            "Diététicien",
            "Conseiller nutrition",
            "Responsable restauration collective",
        ],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "",
    },
    {
        "slug": "bts-professions-immobilieres-paris",
        "name": "BTS Professions Immobilières Paris",
        "type": School.Type.BTS,
        "city": "Paris",
        "region": "Île-de-France",
        "postal_code": "75001",
        "tuition_min_eur": 0,
        "tuition_max_eur": 300,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 3,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "BTS Professions Immobilières pour devenir agent immobilier, gestionnaire de patrimoine ou promoteur.",
        "top_debouches": ["Agent immobilier", "Gestionnaire locatif", "Négociateur immobilier"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "",
    },
    {
        "slug": "bts-tourisme-nice",
        "name": "BTS Tourisme Nice",
        "type": School.Type.BTS,
        "city": "Nice",
        "region": "Provence-Alpes-Côte d'Azur",
        "postal_code": "06000",
        "tuition_min_eur": 0,
        "tuition_max_eur": 300,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 3,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "BTS Tourisme pour former des professionnels du voyage, de l'accueil et de l'événementiel.",
        "top_debouches": ["Agent de voyage", "Guide touristique", "Responsable hôtellerie"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "",
    },
    {
        "slug": "bts-comptabilite-gestion-toulouse",
        "name": "BTS Comptabilité et Gestion Toulouse",
        "type": School.Type.BTS,
        "city": "Toulouse",
        "region": "Occitanie",
        "postal_code": "31000",
        "tuition_min_eur": 0,
        "tuition_max_eur": 200,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 4,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "BTS Comptabilité et Gestion (CG) pour former aux métiers de la comptabilité et du contrôle de gestion.",
        "top_debouches": ["Comptable", "Contrôleur de gestion", "Gestionnaire de paie"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "",
    },
    {
        "slug": "bts-mco-grenoble",
        "name": "BTS MCO Grenoble",
        "type": School.Type.BTS,
        "city": "Grenoble",
        "region": "Auvergne-Rhône-Alpes",
        "postal_code": "38000",
        "tuition_min_eur": 0,
        "tuition_max_eur": 250,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 4,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "BTS Management Commercial Opérationnel (MCO) pour former les futurs managers de points de vente.",
        "top_debouches": ["Manager de rayon", "Responsable commerce", "Chef des ventes"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "",
    },
    {
        "slug": "bts-design-graphique-paris",
        "name": "BTS Design Graphique Paris",
        "type": School.Type.BTS,
        "city": "Paris",
        "region": "Île-de-France",
        "postal_code": "75004",
        "tuition_min_eur": 0,
        "tuition_max_eur": 300,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 2,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "BTS Design Graphique, option médias imprimés et option médias numériques.",
        "top_debouches": ["Graphiste", "Designer UI", "Directeur artistique junior"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "",
    },
    # ── BUT / IUT ──────────────────────────────────────────────────────────
    {
        "slug": "iut-paris-descartes",
        "name": "IUT de Paris - Université Paris Cité",
        "type": School.Type.IUT,
        "city": "Paris",
        "region": "Île-de-France",
        "postal_code": "75006",
        "lat": "48.851600",
        "lon": "2.346600",
        "tuition_min_eur": 0,
        "tuition_max_eur": 500,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 3,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "IUT proposant des BUT en Informatique, Réseaux et Télécoms, Gestion des Entreprises et des Administrations.",
        "top_debouches": ["Développeur", "Administrateur systèmes", "Gestionnaire d'entreprise"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://iutparis.u-paris.fr",
    },
    {
        "slug": "iut-lyon-1-villeurbanne",
        "name": "IUT Lyon 1 - Université Lyon 1",
        "type": School.Type.IUT,
        "city": "Villeurbanne",
        "region": "Auvergne-Rhône-Alpes",
        "postal_code": "69100",
        "lat": "45.783300",
        "lon": "4.879200",
        "tuition_min_eur": 0,
        "tuition_max_eur": 500,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 3,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "IUT formant aux BUT en Informatique, Génie Civil, Chimie, Biologie, Gestion.",
        "top_debouches": ["Analyste données", "Technicien génie civil", "Chargé RH"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://iut.univ-lyon1.fr",
    },
    {
        "slug": "iut-bordeaux-montaigne",
        "name": "IUT Bordeaux Montaigne",
        "type": School.Type.IUT,
        "city": "Bordeaux",
        "region": "Nouvelle-Aquitaine",
        "postal_code": "33400",
        "tuition_min_eur": 0,
        "tuition_max_eur": 500,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 3,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "BUT Carrières sociales, Gestion administrative et commerciale, Information-Communication.",
        "top_debouches": ["Chargé de communication", "Assistant social", "Chargé de projet RH"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "",
    },
    {
        "slug": "but-informatique-montpellier",
        "name": "BUT Informatique - Université Montpellier",
        "type": School.Type.BUT,
        "city": "Montpellier",
        "region": "Occitanie",
        "postal_code": "34095",
        "lat": "43.607600",
        "lon": "3.876700",
        "tuition_min_eur": 0,
        "tuition_max_eur": 500,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 2,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "BUT Informatique parcours Développement d'applications et parcours Administration des systèmes.",
        "top_debouches": ["Développeur full-stack", "DevOps", "Ingénieur logiciel"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "",
    },
    {
        "slug": "but-gestion-rennes",
        "name": "BUT Gestion des Entreprises - Rennes 1",
        "type": School.Type.BUT,
        "city": "Rennes",
        "region": "Bretagne",
        "postal_code": "35000",
        "tuition_min_eur": 0,
        "tuition_max_eur": 500,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 3,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "BUT Gestion des Entreprises et des Administrations parcours RH et Finance.",
        "top_debouches": ["Contrôleur de gestion", "Chargé RH", "Analyste financier"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "",
    },
    {
        "slug": "but-reseaux-telecom-strasbourg",
        "name": "BUT Réseaux et Télécoms - Strasbourg",
        "type": School.Type.BUT,
        "city": "Strasbourg",
        "region": "Grand Est",
        "postal_code": "67000",
        "tuition_min_eur": 0,
        "tuition_max_eur": 500,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 3,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "BUT Réseaux et Télécommunications, cybersécurité et cloud.",
        "top_debouches": ["Ingénieur réseaux", "Expert cybersécurité", "Architecte cloud"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "",
    },
    {
        "slug": "but-sante-paris-saclay",
        "name": "BUT Génie Biologique - Paris-Saclay",
        "type": School.Type.BUT,
        "city": "Orsay",
        "region": "Île-de-France",
        "postal_code": "91400",
        "tuition_min_eur": 0,
        "tuition_max_eur": 500,
        "apprenticeship": False,
        "internship": True,
        "selectivity_index": 2,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "BUT Génie Biologique parcours Analyses biologiques et biochimiques, Agronomie.",
        "top_debouches": ["Technicien de laboratoire", "Agronome", "Analyste médical"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "",
    },
    # ── Prépas ─────────────────────────────────────────────────────────────
    {
        "slug": "prepa-louis-le-grand-paris",
        "name": "CPGE Louis-le-Grand",
        "type": School.Type.PREPA,
        "city": "Paris",
        "region": "Île-de-France",
        "postal_code": "75005",
        "lat": "48.848900",
        "lon": "2.345600",
        "tuition_min_eur": 0,
        "tuition_max_eur": 500,
        "apprenticeship": False,
        "internship": False,
        "selectivity_index": 1,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Classes préparatoires aux grandes écoles MP*, PC*, PSI*, BCPST. L'une des prépas les plus sélectives de France.",
        "top_debouches": ["Polytechnicien", "Normalien", "Ingénieur Mines/Ponts"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://www.louislegrand.fr",
    },
    {
        "slug": "prepa-saint-louis-paris",
        "name": "CPGE Saint-Louis",
        "type": School.Type.PREPA,
        "city": "Paris",
        "region": "Île-de-France",
        "postal_code": "75006",
        "tuition_min_eur": 0,
        "tuition_max_eur": 500,
        "apprenticeship": False,
        "internship": False,
        "selectivity_index": 1,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "CPGE MP, MPSI, PCSI, PSI, BCPST, PTSI et TSI. Établissement référence pour les filières scientifiques.",
        "top_debouches": ["Ingénieur X-Ponts", "Ingénieur Centrale", "Chercheur CNRS"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://www.saintlouis.fr",
    },
    {
        "slug": "prepa-henri-iv-paris",
        "name": "CPGE Henri-IV",
        "type": School.Type.PREPA,
        "city": "Paris",
        "region": "Île-de-France",
        "postal_code": "75005",
        "tuition_min_eur": 0,
        "tuition_max_eur": 500,
        "apprenticeship": False,
        "internship": False,
        "selectivity_index": 1,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Prépas HEC, khâgne, hypokhâgne, MP, PC, BCPST. Fort taux d'admission aux ENS et HEC.",
        "top_debouches": ["Normalien", "HEC Paris", "Sciences Po Paris"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "",
    },
    {
        "slug": "prepa-hypokhagne-sartrouville",
        "name": "CPGE Littéraires - Sartrouville",
        "type": School.Type.PREPA,
        "city": "Sartrouville",
        "region": "Île-de-France",
        "postal_code": "78500",
        "tuition_min_eur": 0,
        "tuition_max_eur": 300,
        "apprenticeship": False,
        "internship": False,
        "selectivity_index": 3,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Hypokhâgne et khâgne pour les filières lettres et sciences humaines.",
        "top_debouches": ["Normalien Lettres", "Journaliste", "Enseignant agrégé"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "",
    },
    # ── Licences et Licences Pro ──────────────────────────────────────────
    {
        "slug": "licence-psychologie-paris5",
        "name": "Licence Psychologie - Université Paris Cité",
        "type": School.Type.LICENCE,
        "city": "Paris",
        "region": "Île-de-France",
        "postal_code": "75006",
        "tuition_min_eur": 0,
        "tuition_max_eur": 600,
        "apprenticeship": False,
        "internship": True,
        "selectivity_index": 4,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Licence de psychologie généraliste, parcours clinique, sociale et cognitive.",
        "top_debouches": [
            "Psychologue (avec master)",
            "Conseiller orientation",
            "Éducateur spécialisé",
        ],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://u-paris.fr",
    },
    {
        "slug": "licence-droit-assas",
        "name": "Licence Droit - Université Paris 2 Panthéon-Assas",
        "type": School.Type.LICENCE,
        "city": "Paris",
        "region": "Île-de-France",
        "postal_code": "75005",
        "lat": "48.849600",
        "lon": "2.347500",
        "tuition_min_eur": 0,
        "tuition_max_eur": 600,
        "apprenticeship": False,
        "internship": False,
        "selectivity_index": 3,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Licence de droit privé, droit public et droit international. Référence nationale pour les études juridiques.",
        "top_debouches": ["Avocat (avec master + barreau)", "Juriste d'entreprise", "Notaire"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://www.u-paris2.fr",
    },
    {
        "slug": "licence-info-jussieu",
        "name": "Licence Informatique - Sorbonne Université",
        "type": School.Type.LICENCE,
        "city": "Paris",
        "region": "Île-de-France",
        "postal_code": "75005",
        "tuition_min_eur": 0,
        "tuition_max_eur": 600,
        "apprenticeship": False,
        "internship": True,
        "selectivity_index": 3,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Licence d'informatique fondamentale, algorithmique, programmation et bases de données.",
        "top_debouches": ["Développeur logiciel", "Data scientist", "Ingénieur IA"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://www.sorbonne-universite.fr",
    },
    {
        "slug": "licence-pro-cybersecurite-cnam",
        "name": "Licence Pro Cybersécurité - CNAM",
        "type": School.Type.LICENCE_PRO,
        "city": "Paris",
        "region": "Île-de-France",
        "postal_code": "75003",
        "tuition_min_eur": 0,
        "tuition_max_eur": 600,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 2,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Licence professionnelle en administration et sécurité des systèmes d'information.",
        "top_debouches": ["Analyste cybersécurité", "Administrateur sécurité", "Auditeur SI"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://www.cnam.fr",
    },
    {
        "slug": "licence-pro-logistique-evry",
        "name": "Licence Pro Logistique - Université Évry",
        "type": School.Type.LICENCE_PRO,
        "city": "Évry-Courcouronnes",
        "region": "Île-de-France",
        "postal_code": "91000",
        "tuition_min_eur": 0,
        "tuition_max_eur": 500,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 3,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "LP Management de la chaîne logistique et transport. Forte insertion professionnelle.",
        "top_debouches": [
            "Responsable logistique",
            "Chef de projet supply chain",
            "Coordinateur transport",
        ],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "",
    },
    {
        "slug": "licence-svt-bordeaux",
        "name": "Licence Sciences de la Vie - Université Bordeaux",
        "type": School.Type.LICENCE,
        "city": "Bordeaux",
        "region": "Nouvelle-Aquitaine",
        "postal_code": "33076",
        "tuition_min_eur": 0,
        "tuition_max_eur": 600,
        "apprenticeship": False,
        "internship": True,
        "selectivity_index": 4,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Licence Sciences de la Vie parcours biologie cellulaire, écologie et physiologie.",
        "top_debouches": [
            "Chercheur (avec master)",
            "Technicien laboratoire",
            "Préparateur en pharmacie",
        ],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "",
    },
    # ── Écoles d'ingénieurs ────────────────────────────────────────────────
    {
        "slug": "polytechnique-palaiseau",
        "name": "École Polytechnique",
        "type": School.Type.ECOLE_INGENIEUR,
        "city": "Palaiseau",
        "region": "Île-de-France",
        "postal_code": "91120",
        "lat": "48.713700",
        "lon": "2.209400",
        "tuition_min_eur": 0,
        "tuition_max_eur": 15000,
        "apprenticeship": False,
        "internship": True,
        "selectivity_index": 1,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Grande école d'ingénieurs, l'une des plus prestigieuses de France. Accès sur concours X.",
        "top_debouches": ["Ingénieur de recherche", "Consultant stratégique", "Entrepreneur tech"],
        "parcoursup_dates": {},
        "official_url": "https://www.polytechnique.edu",
    },
    {
        "slug": "centrale-supelec-gif",
        "name": "CentraleSupélec",
        "type": School.Type.ECOLE_INGENIEUR,
        "city": "Gif-sur-Yvette",
        "region": "Île-de-France",
        "postal_code": "91190",
        "lat": "48.710000",
        "lon": "2.169900",
        "tuition_min_eur": 8000,
        "tuition_max_eur": 12000,
        "apprenticeship": False,
        "internship": True,
        "selectivity_index": 1,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Grande école d'ingénieurs généraliste. Accès sur concours Centrale-Supélec.",
        "top_debouches": ["Ingénieur R&D", "Manager de projet", "Data scientist senior"],
        "parcoursup_dates": {},
        "official_url": "https://www.centralesupelec.fr",
    },
    {
        "slug": "insa-lyon",
        "name": "INSA Lyon",
        "type": School.Type.ECOLE_INGENIEUR,
        "city": "Villeurbanne",
        "region": "Auvergne-Rhône-Alpes",
        "postal_code": "69621",
        "lat": "45.783300",
        "lon": "4.874000",
        "tuition_min_eur": 3000,
        "tuition_max_eur": 7000,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 1,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Institut National des Sciences Appliquées. Formation d'ingénieurs sur 5 ans à partir du bac.",
        "top_debouches": ["Ingénieur génie civil", "Ingénieur informatique", "Ingénieur chimiste"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://www.insa-lyon.fr",
    },
    {
        "slug": "epita-paris",
        "name": "EPITA - École de l'informatique",
        "type": School.Type.ECOLE_INGENIEUR,
        "city": "Le Kremlin-Bicêtre",
        "region": "Île-de-France",
        "postal_code": "94270",
        "lat": "48.809900",
        "lon": "2.355100",
        "tuition_min_eur": 8000,
        "tuition_max_eur": 12000,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 2,
        "public_private": School.PublicPrivate.PRIVE_SOUS_CONTRAT,
        "description": "École d'ingénieurs spécialisée en informatique, sécurité, IA et systèmes embarqués.",
        "top_debouches": ["Ingénieur logiciel", "Expert cybersécurité", "Architecte SI"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://www.epita.fr",
    },
    {
        "slug": "efrei-paris-villejuif",
        "name": "EFREI Paris",
        "type": School.Type.ECOLE_INGENIEUR,
        "city": "Villejuif",
        "region": "Île-de-France",
        "postal_code": "94800",
        "tuition_min_eur": 7000,
        "tuition_max_eur": 11000,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 2,
        "public_private": School.PublicPrivate.PRIVE_SOUS_CONTRAT,
        "description": "École d'ingénieurs du numérique, spécialisée en data, cloud, cybersécurité et IA.",
        "top_debouches": ["Data engineer", "Cloud architect", "Développeur full-stack"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://www.efrei.fr",
    },
    {
        "slug": "telecom-paris-palaiseau",
        "name": "Télécom Paris",
        "type": School.Type.ECOLE_INGENIEUR,
        "city": "Palaiseau",
        "region": "Île-de-France",
        "postal_code": "91120",
        "tuition_min_eur": 3000,
        "tuition_max_eur": 7000,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 1,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Grande école d'ingénieurs spécialisée en numérique, réseaux et IA. Membre de l'Institut Polytechnique de Paris.",
        "top_debouches": ["Ingénieur télécoms", "Data scientist", "Directeur technique"],
        "parcoursup_dates": {},
        "official_url": "https://www.telecom-paris.fr",
    },
    {
        "slug": "arts-et-metiers-paris",
        "name": "Arts et Métiers - Campus de Paris",
        "type": School.Type.ECOLE_INGENIEUR,
        "city": "Paris",
        "region": "Île-de-France",
        "postal_code": "75013",
        "tuition_min_eur": 1000,
        "tuition_max_eur": 5000,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 1,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Grande école d'ingénieurs généraliste, spécialisée en mécanique, matériaux et procédés industriels.",
        "top_debouches": ["Ingénieur mécanique", "Directeur industriel", "Chef de projet R&D"],
        "parcoursup_dates": {},
        "official_url": "https://artsetmetiers.fr",
    },
    {
        "slug": "grenoble-inp-ensimag",
        "name": "Grenoble INP - ENSIMAG",
        "type": School.Type.ECOLE_INGENIEUR,
        "city": "Grenoble",
        "region": "Auvergne-Rhône-Alpes",
        "postal_code": "38000",
        "lat": "45.193600",
        "lon": "5.767500",
        "tuition_min_eur": 4000,
        "tuition_max_eur": 8000,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 1,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "École nationale supérieure d'informatique et mathématiques appliquées. Très forte en IA et finance quantitative.",
        "top_debouches": ["Ingénieur IA", "Quant finance", "Architecte logiciel"],
        "parcoursup_dates": {},
        "official_url": "https://ensimag.grenoble-inp.fr",
    },
    # ── Écoles de Commerce ─────────────────────────────────────────────────
    {
        "slug": "hec-paris-jouy",
        "name": "HEC Paris",
        "type": School.Type.ECOLE_COMMERCE,
        "city": "Jouy-en-Josas",
        "region": "Île-de-France",
        "postal_code": "78350",
        "lat": "48.745000",
        "lon": "2.175700",
        "tuition_min_eur": 15000,
        "tuition_max_eur": 16500,
        "apprenticeship": False,
        "internship": True,
        "selectivity_index": 1,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "La première business school française et l'une des meilleures au monde. Concours HEC.",
        "top_debouches": ["Consultant McKinsey/BCG", "Banquier d'affaires", "Entrepreneur"],
        "parcoursup_dates": {},
        "official_url": "https://www.hec.edu",
    },
    {
        "slug": "essec-cergy",
        "name": "ESSEC Business School",
        "type": School.Type.ECOLE_COMMERCE,
        "city": "Cergy",
        "region": "Île-de-France",
        "postal_code": "95021",
        "lat": "49.032100",
        "lon": "2.079800",
        "tuition_min_eur": 14000,
        "tuition_max_eur": 16000,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 1,
        "public_private": School.PublicPrivate.PRIVE_SOUS_CONTRAT,
        "description": "Grande école de commerce internationale. Forte en luxe, finance et entrepreneuriat.",
        "top_debouches": ["Consultant", "Manager finance", "Directeur marketing"],
        "parcoursup_dates": {},
        "official_url": "https://www.essec.edu",
    },
    {
        "slug": "emlyon-lyon",
        "name": "emlyon business school",
        "type": School.Type.ECOLE_COMMERCE,
        "city": "Lyon",
        "region": "Auvergne-Rhône-Alpes",
        "postal_code": "69130",
        "tuition_min_eur": 11000,
        "tuition_max_eur": 14000,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 2,
        "public_private": School.PublicPrivate.PRIVE_SOUS_CONTRAT,
        "description": "Business school lyonnaise de renommée internationale. Spécialité entrepreneuriat et innovation.",
        "top_debouches": ["Entrepreneur", "Manager innovation", "Directeur commercial"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://www.em-lyon.com",
    },
    {
        "slug": "neoma-rouen",
        "name": "NEOMA Business School",
        "type": School.Type.ECOLE_COMMERCE,
        "city": "Rouen",
        "region": "Normandie",
        "postal_code": "76130",
        "tuition_min_eur": 9000,
        "tuition_max_eur": 13000,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 2,
        "public_private": School.PublicPrivate.PRIVE_SOUS_CONTRAT,
        "description": "NEOMA Business School, fusion de Rouen Business School et Reims Management School.",
        "top_debouches": ["Manager marketing", "Consultant RH", "Chargé d'affaires"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://www.neoma-bs.fr",
    },
    {
        "slug": "kedge-bordeaux",
        "name": "KEDGE Business School",
        "type": School.Type.ECOLE_COMMERCE,
        "city": "Bordeaux",
        "region": "Nouvelle-Aquitaine",
        "postal_code": "33400",
        "tuition_min_eur": 8000,
        "tuition_max_eur": 12000,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 2,
        "public_private": School.PublicPrivate.PRIVE_SOUS_CONTRAT,
        "description": "Business school avec campus à Bordeaux, Marseille et Paris. Spécialisée en supply chain et luxe.",
        "top_debouches": [
            "Acheteur international",
            "Responsable supply chain",
            "Chef de projet marketing",
        ],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://www.kedge.edu",
    },
    {
        "slug": "escp-paris",
        "name": "ESCP Business School",
        "type": School.Type.ECOLE_COMMERCE,
        "city": "Paris",
        "region": "Île-de-France",
        "postal_code": "75011",
        "tuition_min_eur": 13000,
        "tuition_max_eur": 16000,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 1,
        "public_private": School.PublicPrivate.PRIVE_SOUS_CONTRAT,
        "description": "La plus ancienne école de commerce du monde. Multi-campus européen.",
        "top_debouches": ["Banquier d'investissement", "Consultant international", "DG Europe"],
        "parcoursup_dates": {},
        "official_url": "https://www.escp.eu",
    },
    # ── Écoles de Santé ────────────────────────────────────────────────────
    {
        "slug": "ifsi-aphp-paris",
        "name": "IFSI AP-HP Paris",
        "type": School.Type.ECOLE_SANTE,
        "city": "Paris",
        "region": "Île-de-France",
        "postal_code": "75014",
        "lat": "48.818500",
        "lon": "2.327700",
        "tuition_min_eur": 0,
        "tuition_max_eur": 200,
        "apprenticeship": False,
        "internship": True,
        "selectivity_index": 2,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Institut de Formation en Soins Infirmiers rattaché à l'AP-HP. Formation diplôme d'État infirmier (DEI) en 3 ans.",
        "top_debouches": [
            "Infirmier·ère DE",
            "Cadre de santé (avec master)",
            "Infirmier spécialisé (IADE, IBODE)",
        ],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://www.aphp.fr/formation",
    },
    {
        "slug": "ifmk-paris-broca",
        "name": "IFMK Paris Broca",
        "type": School.Type.ECOLE_SANTE,
        "city": "Paris",
        "region": "Île-de-France",
        "postal_code": "75013",
        "tuition_min_eur": 0,
        "tuition_max_eur": 300,
        "apprenticeship": False,
        "internship": True,
        "selectivity_index": 2,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Institut de Formation en Masso-Kinésithérapie. Formation diplôme d'État de masseur-kinésithérapeute en 4 ans.",
        "top_debouches": [
            "Masseur-kinésithérapeute libéral",
            "Kiné hospitalier",
            "Ostéopathe (formation complémentaire)",
        ],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "",
    },
    {
        "slug": "ecole-sages-femmes-necker",
        "name": "École de Sages-Femmes Necker-Enfants Malades",
        "type": School.Type.ECOLE_SANTE,
        "city": "Paris",
        "region": "Île-de-France",
        "postal_code": "75015",
        "tuition_min_eur": 0,
        "tuition_max_eur": 200,
        "apprenticeship": False,
        "internship": True,
        "selectivity_index": 2,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Formation diplôme d'État de sage-femme en 5 ans (1 an PASS + 4 ans maïeutique).",
        "top_debouches": ["Sage-femme hospitalière", "Sage-femme libérale", "Cadre maïeutique"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "",
    },
    {
        "slug": "ifas-lyon-croix-rouge",
        "name": "IFAS Croix-Rouge Lyon",
        "type": School.Type.ECOLE_SANTE,
        "city": "Lyon",
        "region": "Auvergne-Rhône-Alpes",
        "postal_code": "69003",
        "tuition_min_eur": 0,
        "tuition_max_eur": 200,
        "apprenticeship": False,
        "internship": True,
        "selectivity_index": 3,
        "public_private": School.PublicPrivate.PRIVE_SOUS_CONTRAT,
        "description": "Institut de formation des aides-soignants. Formation en 1 an menant au diplôme d'État DEAS.",
        "top_debouches": ["Aide-soignant·e", "AMP", "Futur·e infirmier·ère (poursuite IFSI)"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "",
    },
    {
        "slug": "ifsi-bordeaux-chu",
        "name": "IFSI CHU Bordeaux",
        "type": School.Type.ECOLE_SANTE,
        "city": "Bordeaux",
        "region": "Nouvelle-Aquitaine",
        "postal_code": "33000",
        "tuition_min_eur": 0,
        "tuition_max_eur": 200,
        "apprenticeship": False,
        "internship": True,
        "selectivity_index": 2,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "IFSI rattaché au CHU de Bordeaux. Formation infirmier·ère diplômé·e d'État en 3 ans.",
        "top_debouches": ["Infirmier·ère DE", "Puéricultrice", "Infirmier réanimation"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "",
    },
    # ── Universités ────────────────────────────────────────────────────────
    {
        "slug": "universite-paris-saclay",
        "name": "Université Paris-Saclay",
        "type": School.Type.UNIVERSITE,
        "city": "Saclay",
        "region": "Île-de-France",
        "postal_code": "91190",
        "lat": "48.714100",
        "lon": "2.208400",
        "tuition_min_eur": 0,
        "tuition_max_eur": 700,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 2,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Université de recherche classée dans le top 15 mondial. Forte en sciences, ingénierie et médecine.",
        "top_debouches": ["Chercheur", "Ingénieur R&D", "Médecin (PASS + médecine)"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://www.universite-paris-saclay.fr",
    },
    {
        "slug": "sorbonne-universite-paris",
        "name": "Sorbonne Université",
        "type": School.Type.UNIVERSITE,
        "city": "Paris",
        "region": "Île-de-France",
        "postal_code": "75005",
        "lat": "48.847600",
        "lon": "2.346900",
        "tuition_min_eur": 0,
        "tuition_max_eur": 650,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 3,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Université pluridisciplinaire couvrant lettres, sciences et médecine. Héritière de la Sorbonne historique.",
        "top_debouches": ["Enseignant", "Chercheur", "Professionnel culture/médias"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://www.sorbonne-universite.fr",
    },
    {
        "slug": "universite-lyon1",
        "name": "Université Claude Bernard Lyon 1",
        "type": School.Type.UNIVERSITE,
        "city": "Lyon",
        "region": "Auvergne-Rhône-Alpes",
        "postal_code": "69100",
        "tuition_min_eur": 0,
        "tuition_max_eur": 650,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 3,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Université de sciences, technologies et santé. Forte en médecine, pharmacie, odontologie et sciences du sport.",
        "top_debouches": ["Médecin (PASS + LAS)", "Pharmacien", "Kinésithérapeute"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://www.univ-lyon1.fr",
    },
    {
        "slug": "universite-nantes",
        "name": "Nantes Université",
        "type": School.Type.UNIVERSITE,
        "city": "Nantes",
        "region": "Pays de la Loire",
        "postal_code": "44000",
        "tuition_min_eur": 0,
        "tuition_max_eur": 650,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 4,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Université pluridisciplinaire avec droit, médecine, sciences et lettres.",
        "top_debouches": ["Juriste", "Enseignant", "Développeur logiciel"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://www.univ-nantes.fr",
    },
    {
        "slug": "universite-strasbourg",
        "name": "Université de Strasbourg",
        "type": School.Type.UNIVERSITE,
        "city": "Strasbourg",
        "region": "Grand Est",
        "postal_code": "67081",
        "tuition_min_eur": 0,
        "tuition_max_eur": 650,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 3,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Grande université rhénane, pluridisciplinaire. Reconnue pour le droit européen et la médecine.",
        "top_debouches": ["Juriste droit européen", "Médecin", "Chercheur en chimie"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://www.unistra.fr",
    },
    {
        "slug": "universite-toulouse-capitole",
        "name": "Université Toulouse Capitole",
        "type": School.Type.UNIVERSITE,
        "city": "Toulouse",
        "region": "Occitanie",
        "postal_code": "31042",
        "tuition_min_eur": 0,
        "tuition_max_eur": 650,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 3,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Université de droit, économie, gestion et informatique. Référence nationale en droit des affaires.",
        "top_debouches": ["Avocat d'affaires", "Fiscaliste", "Data analyst (parcours Gestion)"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://www.ut-capitole.fr",
    },
    {
        "slug": "universite-aix-marseille",
        "name": "Aix-Marseille Université",
        "type": School.Type.UNIVERSITE,
        "city": "Aix-en-Provence",
        "region": "Provence-Alpes-Côte d'Azur",
        "postal_code": "13621",
        "tuition_min_eur": 0,
        "tuition_max_eur": 650,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 4,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "La plus grande université de France par nombre d'étudiants. Forte en médecine, droit et sciences.",
        "top_debouches": ["Médecin", "Juriste", "Ingénieur (double diplôme)"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://www.univ-amu.fr",
    },
    {
        "slug": "universite-lille",
        "name": "Université de Lille",
        "type": School.Type.UNIVERSITE,
        "city": "Lille",
        "region": "Hauts-de-France",
        "postal_code": "59650",
        "tuition_min_eur": 0,
        "tuition_max_eur": 650,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 4,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Université pluridisciplinaire du Nord, forte en médecine, ingénierie et sciences humaines.",
        "top_debouches": ["Médecin généraliste", "Ingénieur chimiste", "Enseignant-chercheur"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://www.univ-lille.fr",
    },
    {
        "slug": "universite-rennes1",
        "name": "Université de Rennes",
        "type": School.Type.UNIVERSITE,
        "city": "Rennes",
        "region": "Bretagne",
        "postal_code": "35000",
        "tuition_min_eur": 0,
        "tuition_max_eur": 650,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 4,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Université pluridisciplinaire bretonne, reconnue pour l'informatique, le droit et les sciences.",
        "top_debouches": ["Développeur", "Juriste", "Chercheur biologie"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://www.univ-rennes.fr",
    },
    {
        "slug": "universite-paris-dauphine",
        "name": "Université Paris-Dauphine - PSL",
        "type": School.Type.UNIVERSITE,
        "city": "Paris",
        "region": "Île-de-France",
        "postal_code": "75016",
        "lat": "48.862100",
        "lon": "2.287200",
        "tuition_min_eur": 200,
        "tuition_max_eur": 1500,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 2,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Université sélective de sciences des organisations, finance et économie. Intégrée dans PSL.",
        "top_debouches": ["Analyste financier", "Consultant", "Actuaire"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://dauphine.psl.eu",
    },
    {
        "slug": "universite-grenoble-alpes",
        "name": "Université Grenoble Alpes",
        "type": School.Type.UNIVERSITE,
        "city": "Grenoble",
        "region": "Auvergne-Rhône-Alpes",
        "postal_code": "38400",
        "tuition_min_eur": 0,
        "tuition_max_eur": 650,
        "apprenticeship": True,
        "internship": True,
        "selectivity_index": 3,
        "public_private": School.PublicPrivate.PUBLIC,
        "description": "Université de recherche pluridisciplinaire forte en physique, nanotechnologies et sciences sociales.",
        "top_debouches": ["Physicien", "Ingénieur nanotechnologies", "Géographe-urbaniste"],
        "parcoursup_dates": {"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"},
        "official_url": "https://www.univ-grenoble-alpes.fr",
    },
]

# ---------------------------------------------------------------------------
# Formations seed data (inline per school)
# ---------------------------------------------------------------------------

FORMATIONS_BY_SCHOOL_SLUG: dict[str, list[dict]] = {
    "polytechnique-palaiseau": [
        {
            "name": "Cycle ingénieur polytechnicien",
            "duration_years": 3,
            "parcoursup_open": False,
            "affelnet_open": False,
        },
    ],
    "centrale-supelec-gif": [
        {
            "name": "Cycle ingénieur généraliste CentraleSupélec",
            "duration_years": 3,
            "parcoursup_open": False,
            "affelnet_open": False,
        },
    ],
    "hec-paris-jouy": [
        {
            "name": "Grande École HEC",
            "duration_years": 3,
            "parcoursup_open": False,
            "affelnet_open": False,
        },
        {
            "name": "HEC Entrepreneurs",
            "duration_years": 2,
            "parcoursup_open": False,
            "affelnet_open": False,
        },
    ],
    "ifsi-aphp-paris": [
        {
            "name": "Diplôme d'État Infirmier (DEI)",
            "duration_years": 3,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
    ],
    "ifsi-bordeaux-chu": [
        {
            "name": "Diplôme d'État Infirmier (DEI)",
            "duration_years": 3,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
    ],
    "ifmk-paris-broca": [
        {
            "name": "Diplôme d'État Masseur-Kinésithérapeute (DEMK)",
            "duration_years": 4,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
    ],
    "ecole-sages-femmes-necker": [
        {
            "name": "Diplôme d'État Sage-Femme",
            "duration_years": 5,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
    ],
    "ifas-lyon-croix-rouge": [
        {
            "name": "Diplôme d'État Aide-Soignant (DEAS)",
            "duration_years": 1,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
    ],
    "iut-paris-descartes": [
        {
            "name": "BUT Informatique parcours Développement",
            "duration_years": 3,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
        {
            "name": "BUT Gestion des Entreprises et des Administrations",
            "duration_years": 3,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
    ],
    "iut-lyon-1-villeurbanne": [
        {
            "name": "BUT Informatique parcours Data",
            "duration_years": 3,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
        {
            "name": "BUT Chimie",
            "duration_years": 3,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
    ],
    "insa-lyon": [
        {
            "name": "Cycle ingénieur Informatique",
            "duration_years": 5,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
        {
            "name": "Cycle ingénieur Génie Civil",
            "duration_years": 5,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
        {
            "name": "Cycle ingénieur Biochimie",
            "duration_years": 5,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
    ],
    "epita-paris": [
        {
            "name": "Cycle ingénieur EPITA - Sécurité informatique",
            "duration_years": 5,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
        {
            "name": "Cycle ingénieur EPITA - Intelligence artificielle",
            "duration_years": 5,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
    ],
    "bts-communication-lyon": [
        {
            "name": "BTS Communication",
            "duration_years": 2,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
    ],
    "bts-mco-grenoble": [
        {
            "name": "BTS Management Commercial Opérationnel (MCO)",
            "duration_years": 2,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
    ],
    "bts-comptabilite-gestion-toulouse": [
        {
            "name": "BTS Comptabilité et Gestion (CG)",
            "duration_years": 2,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
    ],
    "bts-dietetique-nantes": [
        {
            "name": "BTS Diététique",
            "duration_years": 2,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
    ],
    "bts-service-num-bordeaux": [
        {
            "name": "BTS SIO option SLAM",
            "duration_years": 2,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
        {
            "name": "BTS SIO option SISR",
            "duration_years": 2,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
    ],
    "licence-psychologie-paris5": [
        {
            "name": "Licence Psychologie",
            "duration_years": 3,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
    ],
    "licence-droit-assas": [
        {
            "name": "Licence Droit privé",
            "duration_years": 3,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
        {
            "name": "Licence Droit public",
            "duration_years": 3,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
    ],
    "universite-paris-saclay": [
        {
            "name": "Licence Sciences pour la Santé (PASS)",
            "duration_years": 1,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
        {
            "name": "Licence Physique-Chimie",
            "duration_years": 3,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
        {
            "name": "Master Mathématiques et Applications",
            "duration_years": 2,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
    ],
    "sorbonne-universite-paris": [
        {
            "name": "Licence Informatique",
            "duration_years": 3,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
        {
            "name": "Licence Sciences de la Terre",
            "duration_years": 3,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
        {
            "name": "Licence Lettres Modernes",
            "duration_years": 3,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
    ],
    "universite-paris-dauphine": [
        {
            "name": "Licence Économie-Gestion",
            "duration_years": 3,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
        {
            "name": "Licence MIDO (Maths-Informatique-Décision-Organisation)",
            "duration_years": 3,
            "parcoursup_open": True,
            "affelnet_open": False,
        },
    ],
}


# ---------------------------------------------------------------------------
# Parcours seed data — Story 4.7
# ---------------------------------------------------------------------------

# Bac Pro parcours (troisieme_bac_pro) — AC6 requires >= 4
PARCOURS_SEED = [
    # 1. Technicien aéronautique — troisieme_bac_pro
    {
        "profession_slug": "technicien-aeronautique",
        "profession_defaults": {
            "name": "Technicien aéronautique",
            "description": (
                "Le technicien aéronautique assure la maintenance et la réparation "
                "des aéronefs et de leurs équipements."
            ),
            "daily_routine": (
                "Tu commences ta matinée en inspectant les systèmes avioniques de "
                "l'aéronef, puis tu procèdes aux vérifications réglementaires."
            ),
            "requirements_json": [{"type": "skill", "label": "Mécanique aéronautique"}],
            "prospects_text": "Technicien avionique, Ingénieur maintenance aéronautique.",
            "signals_json": {
                "passions": ["aviation", "mécanique"],
                "keywords": ["aéronautique", "avion", "maintenance"],
            },
            "level_compatibility": ["lycee_1ere_tle_pro", "college_3eme"],
        },
        "target_school_slug": "lycee-pro-saint-exupery-marseille",
        "niveau_scolaire": Parcours.NiveauScolaire.TROISIEME_BAC_PRO,
        "is_default": True,
        "label": "Voie bac pro aéronautique depuis la 3ème",
        "nodes": [
            {"id": "start", "label": "3ème", "type": "start"},
            {
                "id": "node1",
                "label": "Bac Pro Aéronautique option Avionique",
                "type": "diplome",
                "schoolSlug": "lycee-pro-saint-exupery-marseille",
            },
            {"id": "node2", "label": "BTS Aéronautique", "type": "diplome"},
            {
                "id": "target",
                "label": "Poursuite école d'ingé en alternance",
                "type": "target",
                "schoolSlug": None,
            },
        ],
        "edges": [
            {"source": "start", "target": "node1"},
            {"source": "node1", "target": "node2"},
            {"source": "node2", "target": "target"},
        ],
    },
    # 2. Cuisinier — troisieme_bac_pro
    {
        "profession_slug": "cuisinier",
        "profession_defaults": {
            "name": "Cuisinier",
            "description": (
                "Le cuisinier prépare et réalise des mets variés pour les clients "
                "d'un restaurant ou d'une collectivité."
            ),
            "daily_routine": (
                "Tu commences ta matinée en préparant les ingrédients du service du "
                "midi, puis tu élabores les plats selon les recettes du chef."
            ),
            "requirements_json": [{"type": "skill", "label": "Techniques culinaires"}],
            "prospects_text": "Chef de partie, Sous-chef, Chef de cuisine.",
            "signals_json": {
                "passions": ["cuisine", "gastronomie"],
                "keywords": ["cuisine", "restauration", "gastronomie"],
            },
            "level_compatibility": ["lycee_1ere_tle_pro", "college_3eme"],
        },
        "target_school_slug": "lycee-pro-nicolas-appert-orvault",
        "niveau_scolaire": Parcours.NiveauScolaire.TROISIEME_BAC_PRO,
        "is_default": True,
        "label": "Voie bac pro cuisine depuis la 3ème",
        "nodes": [
            {"id": "start", "label": "3ème", "type": "start"},
            {
                "id": "node1",
                "label": "CAP Cuisine",
                "type": "diplome",
                "schoolSlug": "lycee-pro-nicolas-appert-orvault",
            },
            {
                "id": "node2",
                "label": "Bac Pro Cuisine",
                "type": "diplome",
                "schoolSlug": "lycee-pro-nicolas-appert-orvault",
            },
            {
                "id": "target",
                "label": "Chef de cuisine",
                "type": "target",
                "schoolSlug": None,
            },
        ],
        "edges": [
            {"source": "start", "target": "node1"},
            {"source": "node1", "target": "node2"},
            {"source": "node2", "target": "target"},
        ],
    },
    # 3. Électricien — troisieme_bac_pro
    {
        "profession_slug": "electricien",
        "profession_defaults": {
            "name": "Électricien",
            "description": (
                "L'électricien installe, entretient et répare les installations "
                "électriques dans les bâtiments et les industries."
            ),
            "daily_routine": (
                "Tu commences ta matinée en lisant les plans électriques du chantier, "
                "puis tu poses les câbles et raccordes les armoires électriques."
            ),
            "requirements_json": [{"type": "skill", "label": "Électrotechnique"}],
            "prospects_text": "Chef d'équipe électricité, Technicien de maintenance, Conducteur de travaux.",
            "signals_json": {
                "passions": ["électricité", "technique"],
                "keywords": ["électricien", "bâtiment", "énergie"],
            },
            "level_compatibility": ["lycee_1ere_tle_pro", "college_3eme"],
        },
        "target_school_slug": "lycee-pro-leonard-de-vinci-melun",
        "niveau_scolaire": Parcours.NiveauScolaire.TROISIEME_BAC_PRO,
        "is_default": True,
        "label": "Voie bac pro électrotechnique depuis la 3ème",
        "nodes": [
            {"id": "start", "label": "3ème", "type": "start"},
            {
                "id": "node1",
                "label": "Bac Pro Électrotechnique",
                "type": "diplome",
                "schoolSlug": "lycee-pro-leonard-de-vinci-melun",
            },
            {"id": "node2", "label": "BTS Électrotechnique", "type": "diplome"},
            {
                "id": "target",
                "label": "Technicien électricien senior",
                "type": "target",
                "schoolSlug": None,
            },
        ],
        "edges": [
            {"source": "start", "target": "node1"},
            {"source": "node1", "target": "node2"},
            {"source": "node2", "target": "target"},
        ],
    },
    # 4. Mécanicien auto — troisieme_bac_pro
    {
        "profession_slug": "mecanicien-auto",
        "profession_defaults": {
            "name": "Mécanicien automobile",
            "description": (
                "Le mécanicien automobile assure la maintenance, le diagnostic "
                "et la réparation des véhicules."
            ),
            "daily_routine": (
                "Tu commences ta matinée en accueillant les véhicules en atelier, "
                "puis tu réalises les diagnostics via les outils informatiques."
            ),
            "requirements_json": [{"type": "skill", "label": "Mécanique automobile"}],
            "prospects_text": "Chef d'atelier, Expert technique, Diagnosticien.",
            "signals_json": {
                "passions": ["automobile", "mécanique"],
                "keywords": ["mécanique", "automobile", "moteur"],
            },
            "level_compatibility": ["lycee_1ere_tle_pro", "college_3eme"],
        },
        "target_school_slug": "lycee-pro-saint-exupery-marseille",
        "niveau_scolaire": Parcours.NiveauScolaire.TROISIEME_BAC_PRO,
        "is_default": True,
        "label": "Voie bac pro maintenance auto depuis la 3ème",
        "nodes": [
            {"id": "start", "label": "3ème", "type": "start"},
            {
                "id": "node1",
                "label": "Bac Pro Maintenance Auto",
                "type": "diplome",
                "schoolSlug": "lycee-pro-saint-exupery-marseille",
            },
            {"id": "node2", "label": "BTS MAVA", "type": "diplome"},
            {
                "id": "target",
                "label": "Chef d'atelier automobile",
                "type": "target",
                "schoolSlug": None,
            },
        ],
        "edges": [
            {"source": "start", "target": "node1"},
            {"source": "node1", "target": "node2"},
            {"source": "node2", "target": "target"},
        ],
    },
    # 5. Technicien aéronautique — terminale_generale
    {
        "profession_slug": "technicien-aeronautique",
        "target_school_slug": "insa-lyon",
        "niveau_scolaire": Parcours.NiveauScolaire.TERMINALE_GENERALE,
        "is_default": False,
        "label": "Voie terminale générale → INSA",
        "nodes": [
            {"id": "start", "label": "Terminale Générale (Maths/PC)", "type": "start"},
            {"id": "node1", "label": "CPGE PTSI", "type": "diplome"},
            {
                "id": "target",
                "label": "INSA Lyon — Génie Mécanique",
                "type": "target",
                "schoolSlug": "insa-lyon",
            },
        ],
        "edges": [
            {"source": "start", "target": "node1"},
            {"source": "node1", "target": "target"},
        ],
    },
    # 6. Cuisinier — terminale_generale
    {
        "profession_slug": "cuisinier",
        "target_school_slug": None,
        "niveau_scolaire": Parcours.NiveauScolaire.TERMINALE_GENERALE,
        "is_default": False,
        "label": "Voie terminale générale vers la restauration gastronomique",
        "nodes": [
            {"id": "start", "label": "Terminale Générale", "type": "start"},
            {"id": "node1", "label": "BTS Hôtellerie-Restauration", "type": "diplome"},
            {
                "id": "target",
                "label": "Chef de cuisine gastronomique",
                "type": "target",
                "schoolSlug": None,
            },
        ],
        "edges": [
            {"source": "start", "target": "node1"},
            {"source": "node1", "target": "target"},
        ],
    },
]


class Command(BaseCommand):
    help = "Seed the schools & formations referential with 100+ French educational institutions."

    def add_arguments(self, parser):
        parser.add_argument(
            "--clear",
            action="store_true",
            help="Clear existing data before seeding.",
        )

    def handle(self, *args, **options):
        if options["clear"]:
            deleted, _ = School.objects.all().delete()
            self.stdout.write(
                self.style.WARNING(f"Cleared {deleted} schools (and cascaded formations).")
            )

        created_schools = 0
        updated_schools = 0
        created_formations = 0

        with transaction.atomic():
            for data in SCHOOLS_DATA:
                formations_data = FORMATIONS_BY_SCHOOL_SLUG.get(data["slug"], [])
                school_fields = {k: v for k, v in data.items()}

                school, created = School.objects.update_or_create(
                    slug=school_fields.pop("slug"),
                    defaults=school_fields,
                )
                if created:
                    created_schools += 1
                else:
                    updated_schools += 1

                for f_data in formations_data:
                    _, f_created = Formation.objects.get_or_create(
                        school=school,
                        name=f_data["name"],
                        defaults={
                            "duration_years": f_data["duration_years"],
                            "parcoursup_open": f_data["parcoursup_open"],
                            "affelnet_open": f_data["affelnet_open"],
                        },
                    )
                    if f_created:
                        created_formations += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Done. Created {created_schools} schools, updated {updated_schools}. "
                f"Created {created_formations} formations."
            )
        )
        self.stdout.write(f"Total schools in DB: {School.objects.count()}")
        self.stdout.write(f"Total formations in DB: {Formation.objects.count()}")

        # Story 4.7 — seed parcours
        self._seed_parcours()

    def _seed_parcours(self) -> None:
        """Seed parcours entries (Story 4.7). Idempotent via update_or_create."""
        # Import here to avoid circular import at module load time
        from apps.professions.models import Profession

        created_count = 0
        updated_count = 0

        with transaction.atomic():
            for entry in PARCOURS_SEED:
                profession_slug = entry["profession_slug"]
                profession_defaults = entry.get("profession_defaults")

                # Get or create the profession (for test/seed environments)
                if profession_defaults:
                    profession, _ = Profession.objects.get_or_create(
                        slug=profession_slug,
                        defaults=profession_defaults,
                    )
                else:
                    try:
                        profession = Profession.objects.get(slug=profession_slug)
                    except Profession.DoesNotExist:
                        self.stdout.write(
                            self.style.WARNING(
                                f"Parcours skipped: profession '{profession_slug}' not found."
                            )
                        )
                        continue

                # Resolve target school (may be None)
                target_school = None
                if entry.get("target_school_slug"):
                    target_school = School.objects.filter(slug=entry["target_school_slug"]).first()

                niveau = entry["niveau_scolaire"]

                # update_or_create on (profession, target_school, niveau_scolaire)
                _parcours, created = Parcours.objects.update_or_create(
                    profession=profession,
                    target_school=target_school,
                    niveau_scolaire=niveau,
                    defaults={
                        "is_default": entry.get("is_default", False),
                        "label": entry.get("label", ""),
                        "nodes": entry.get("nodes", []),
                        "edges": entry.get("edges", []),
                    },
                )
                if created:
                    created_count += 1
                else:
                    updated_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Parcours seeded: {created_count} created, {updated_count} updated. "
                f"Total bac pro parcours: "
                f"{Parcours.objects.filter(niveau_scolaire=Parcours.NiveauScolaire.TROISIEME_BAC_PRO).count()}"
            )
        )
