"""Reusable FastAPI dependencies — JWT verification for service-to-service auth."""

from __future__ import annotations

import jwt
from fastapi import Header, HTTPException, status

from src.config import settings

_UNAUTHORIZED = HTTPException(
    status_code=status.HTTP_401_UNAUTHORIZED,
    detail="Invalid or missing JWT token",
)


async def verify_jwt(authorization: str | None = Header(default=None)) -> dict:
    """Verify HS256 JWT token generated by Django for service-to-service calls."""
    if not authorization or not authorization.lower().startswith("bearer "):
        raise _UNAUTHORIZED
    token = authorization.split(" ", 1)[1]
    try:
        payload: dict = jwt.decode(
            token,
            settings.jwt_secret,
            algorithms=[settings.jwt_algorithm],
        )
        return payload
    except (jwt.ExpiredSignatureError, jwt.InvalidTokenError) as exc:
        raise _UNAUTHORIZED from exc
