# Generated by Django 5.1.15 on 2026-09-06 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.outreach.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("professions", "0005_level_compatibility_jsonfield"),
        ("schools", "0005_favoriteschool_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EarlyOutreachRequest",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.outreach.models._default_outreach_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "motivation_text",
                    models.TextField(
                        blank=True,
                        help_text="200-500 words optional free-text motivation (Story 5.5 adds moderation).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("responded", "École a répondu"),
                            ("expired_7d", "Expiré (7 jours sans réponse)"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parcours",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="early_outreach_requests",
                        to="schools.parcours",
                    ),
                ),
                (
                    "profession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="early_outreach_requests",
                        to="professions.profession",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="early_outreach_requests",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="early_outreach_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "early_outreach_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "created_at"], name="early_outre_student_b0d7b9_idx"
                    )
                ],
            },
        ),
    ]
