# Generated by Django 5.1.15 on 2026-09-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="earlyoutreachrequest",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="Set when `status=rejected` — explains why to the student (Story 5.5 AC).",
            ),
        ),
        migrations.AlterField(
            model_name="earlyoutreachrequest",
            name="motivation_text",
            field=models.TextField(
                blank=True,
                help_text="Optional free-text motivation, 200-500 words when present (Story 5.5). Gates the request into `pending_moderation` until a path_admin approves/rejects it.",
            ),
        ),
        migrations.AlterField(
            model_name="earlyoutreachrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("pending_moderation", "Motivation en cours de relecture"),
                    ("rejected", "Motivation refusée"),
                    ("responded", "École a répondu"),
                    ("expired_7d", "Expiré (7 jours sans réponse)"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
