# Generated by Django 5.1.15 on 2026-09-06 15:08

import django.db.models.deletion
from django.db import migrations, models

import apps.outreach.models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0002_earlyoutreachrequest_rejection_reason_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EarlyOutreachResponse",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.outreach.models._default_response_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("interested", "Profil intéressant"),
                            ("not_aligned", "Profil non aligné"),
                            ("interview_requested", "Demande d'entretien"),
                        ],
                        max_length=30,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("proposed_slots", models.JSONField(blank=True, default=list)),
                ("accepted_slot", models.CharField(blank=True, max_length=40)),
                ("alternative_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response",
                        to="outreach.earlyoutreachrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Early Outreach Response",
                "verbose_name_plural": "Early Outreach Responses",
                "db_table": "early_outreach_responses",
            },
        ),
    ]
