# Generated by Django 5.1.15 on 2026-09-26 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0003_earlyoutreachresponse"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="earlyoutreachrequest",
            name="rejection_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("contenu_inapproprie", "Contenu inapproprié"),
                    ("donnees_tierces", "Données personnelles de tiers"),
                    ("discrimination", "Discrimination"),
                    ("autre", "Autre"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="earlyoutreachresponse",
            name="comment_moderated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="earlyoutreachresponse",
            name="comment_moderated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="earlyoutreachresponse",
            name="comment_status",
            field=models.CharField(
                choices=[
                    ("approved", "Approuvé"),
                    ("pending", "En attente de modération"),
                    ("rejected", "Rejeté"),
                ],
                default="approved",
                max_length=12,
            ),
        ),
    ]
