# Generated by Django 5.1.15 on 2026-09-27 11:39

import django.db.models.deletion
from django.db import migrations, models

import apps.outreach.models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0004_earlyoutreachrequest_rejection_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewMeeting",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.outreach.models._default_meeting_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(db_index=True)),
                (
                    "room_slug",
                    models.CharField(
                        default=apps.outreach.models._default_room_slug, max_length=64, unique=True
                    ),
                ),
                ("reminder_24h_sent_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_1h_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outreach",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting",
                        to="outreach.earlyoutreachrequest",
                    ),
                ),
            ],
            options={
                "db_table": "interview_meetings",
            },
        ),
    ]
