# Generated by Django 5.1.15 on 2026-09-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RumVital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("LCP", "Largest Contentful Paint"),
                            ("CLS", "Cumulative Layout Shift"),
                            ("INP", "Interaction to Next Paint"),
                            ("TTFB", "Time To First Byte"),
                            ("FCP", "First Contentful Paint"),
                        ],
                        max_length=8,
                    ),
                ),
                ("value", models.FloatField()),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("good", "good"),
                            ("needs-improvement", "needs-improvement"),
                            ("poor", "poor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("home", "Accueil public"),
                            ("metier_fiche", "Fiche métier publique"),
                            ("formation_fiche", "Fiche formation publique"),
                            ("devenir_landing", "Landing devenir-{métier}"),
                            ("niveau_landing", "Landing quel-bac-pour-{métier}"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        choices=[("mobile", "Mobile"), ("desktop", "Desktop")], max_length=10
                    ),
                ),
                (
                    "connection",
                    models.CharField(
                        choices=[
                            ("slow-2g", "slow-2g"),
                            ("2g", "2g"),
                            ("3g", "3g"),
                            ("4g", "4g"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "rum_vitals",
                "indexes": [
                    models.Index(
                        fields=["metric", "page_type", "created_at"],
                        name="rum_vitals_metric_7964d0_idx",
                    )
                ],
            },
        ),
    ]
