# Generated by Django 5.1.15 on 2026-06-21 10:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("professions", "0004_remove_profession_professions_signals_json_gin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("lycee_pro", "Lycée Pro"),
                            ("bts", "BTS"),
                            ("but", "BUT"),
                            ("iut", "IUT"),
                            ("prepa", "Prépa"),
                            ("licence", "Licence"),
                            ("licence_pro", "Licence Pro"),
                            ("ecole_ingenieur", "École d'Ingénieurs"),
                            ("ecole_commerce", "École de Commerce"),
                            ("ecole_sante", "École de Santé"),
                            ("universite", "Université"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=10)),
                ("lat", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("lon", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("tuition_min_eur", models.IntegerField(blank=True, null=True)),
                ("tuition_max_eur", models.IntegerField(blank=True, null=True)),
                ("apprenticeship", models.BooleanField(default=False)),
                ("internship", models.BooleanField(default=False)),
                (
                    "selectivity_index",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=3,
                        help_text="1 = très sélectif (grandes écoles), 5 = non sélectif (université ouverte)",
                    ),
                ),
                (
                    "public_private",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("prive_sous_contrat", "Privé sous contrat"),
                            ("prive_hors_contrat", "Privé hors contrat"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "top_debouches",
                    models.JSONField(default=list, help_text='["Métier 1", "Métier 2", ...]'),
                ),
                (
                    "parcoursup_dates",
                    models.JSONField(
                        default=dict,
                        help_text='{"open": "2026-01-15", "close": "2026-03-10", "results": "2026-06-05"}',
                    ),
                ),
                (
                    "affelnet_dates",
                    models.JSONField(
                        default=dict, help_text='{"open": "2026-01-20", "close": "2026-03-10"}'
                    ),
                ),
                ("official_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["type"], name="schools_sch_type_722c7b_idx"),
                    models.Index(fields=["region"], name="schools_sch_region_367bad_idx"),
                    models.Index(fields=["city"], name="schools_sch_city_356148_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("duration_years", models.IntegerField()),
                ("parcoursup_open", models.BooleanField(default=False)),
                ("affelnet_open", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_metiers",
                    models.ManyToManyField(
                        blank=True, related_name="formations", to="professions.profession"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formations",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formation",
                "verbose_name_plural": "Formations",
                "ordering": ["name"],
            },
        ),
    ]
