# Generated by Django 5.1.15 on 2026-06-21 18:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionStat",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("min_proba", models.IntegerField()),
                ("expected_proba", models.IntegerField()),
                ("max_proba", models.IntegerField()),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("audacieux", "Pari audacieux"),
                            ("realiste", "Pari réaliste"),
                            ("sur", "Valeur sûre"),
                            ("estimation_indicative", "Estimation indicative"),
                        ],
                        max_length=30,
                    ),
                ),
                ("context_line", models.CharField(max_length=300)),
                ("action_lever", models.CharField(blank=True, max_length=300)),
                ("previous_proba", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admission_stats",
                        to="schools.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="None = population baseline",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admission_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admission Stat",
                "verbose_name_plural": "Admission Stats",
                "unique_together": {("school", "user")},
            },
        ),
    ]
