# Generated by Django 5.1.15 on 2026-06-21 22:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professions", "0004_remove_profession_professions_signals_json_gin_and_more"),
        ("schools", "0002_admissionstat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parcours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("nodes", models.JSONField(default=list, help_text="List of node dicts.")),
                ("edges", models.JSONField(default=list, help_text="List of edge dicts.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcours",
                        to="professions.profession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parcours",
                "verbose_name_plural": "Parcours",
                "ordering": ["title"],
            },
        ),
    ]
