# Generated by Django 5.1.15 on 2026-06-21 22:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professions", "0004_remove_profession_professions_signals_json_gin_and_more"),
        ("schools", "0002_admissionstat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parcours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "niveau_scolaire",
                    models.CharField(
                        choices=[
                            ("troisieme_bac_pro", "3ème → Bac Pro"),
                            ("terminale_generale", "Terminale Générale"),
                            ("terminale_technologique", "Terminale Technologique"),
                            ("terminale_pro", "Terminale Pro"),
                            ("autre", "Autre"),
                        ],
                        default="terminale_generale",
                        max_length=30,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="True = recommended parcours for this (profession, niveau_scolaire) pair.",
                    ),
                ),
                (
                    "nodes",
                    models.JSONField(
                        default=list,
                        help_text='[{"id": "n1", "label": "Bac Pro", "type": "diplome", "schoolSlug": "..."}]',
                    ),
                ),
                (
                    "edges",
                    models.JSONField(
                        default=list, help_text='[{"source": "n1", "target": "n2", "weight": 1}]'
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Short descriptive label for this parcours alternative.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcours",
                        to="professions.profession",
                    ),
                ),
                (
                    "target_school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parcours",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parcours",
                "verbose_name_plural": "Parcours",
                "ordering": ["-is_default", "niveau_scolaire"],
                "indexes": [
                    models.Index(
                        fields=["profession", "niveau_scolaire"],
                        name="schools_par_profess_40b462_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("profession", "niveau_scolaire"),
                        name="parcours_unique_default_per_profession_niveau",
                    )
                ],
            },
        ),
    ]
