# Generated by Django 5.1.15 on 2026-06-21 23:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0004_merge_story45_story47"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteSchool",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Favorite School",
                "verbose_name_plural": "Favorite Schools",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="parcours",
            new_name="schools_par_profess_40b462_idx",
            old_name="schools_par_profess_47_idx",
        ),
        migrations.AddField(
            model_name="school",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="school",
            name="school_type",
            field=models.CharField(
                blank=True, help_text="e.g. IFSI, IUT, Lycée pro, Université", max_length=80
            ),
        ),
        migrations.AlterField(
            model_name="parcours",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="parcours",
            name="niveau_scolaire",
            field=models.CharField(
                blank=True,
                help_text="e.g. troisieme_bac_pro, terminale_generale — empty = all levels",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="favoriteschool",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="favoriteschool",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_schools",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favoriteschool",
            unique_together={("user", "school")},
        ),
    ]
