# Generated by Django 5.1.15 on 2026-09-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0006_schoolstaff"),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionstat",
            name="outreach_delta_applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
