# Generated by Django 5.1.15 on 2026-09-26 20:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0007_admissionstat_outreach_delta_applied_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="status",
            field=models.CharField(
                choices=[("draft", "Brouillon"), ("published", "Publié"), ("archived", "Archivé")],
                db_index=True,
                default="published",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="SchoolRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("snapshot", models.JSONField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Création"),
                            ("updated", "Modification"),
                            ("status_changed", "Changement de statut"),
                            ("rolled_back", "Rollback"),
                            ("imported", "Import CSV"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restored_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="schools.schoolrevision",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "school_revisions",
                "ordering": ["-created_at"],
            },
        ),
    ]
