# Generated by Django 5.1.15 on 2026-06-19 21:10

import apps.students.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLevelProfile',
            fields=[
                ('id', models.CharField(default=apps.students.models._default_level_profile_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('level', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('filiere', models.CharField(blank=True, max_length=10, null=True)),
                ('sous_filiere_techno', models.CharField(blank=True, max_length=10, null=True)),
                ('specialites', models.JSONField(blank=True, default=list)),
                ('intended_track', models.CharField(blank=True, max_length=15, null=True)),
                ('postbac_year', models.CharField(blank=True, max_length=15, null=True)),
                ('postbac_formation_type', models.CharField(blank=True, max_length=25, null=True)),
                ('onboarding_step2_status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('skipped', 'Reporté')], db_index=True, default='pending', max_length=15)),
                ('onboarding_step2_completed_at', models.DateTimeField(blank=True, null=True)),
                ('level_ref_version', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_level_profiles',
            },
        ),
        migrations.RenameIndex(
            model_name='studentprofile',
            new_name='student_pro_onboard_9f1ae2_idx',
            old_name='student_pro_onboard_e57bf3_idx',
        ),
        migrations.AddField(
            model_name='studentlevelprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='level_profile', to='students.studentprofile'),
        ),
    ]
