# Generated by Django 5.1.15 on 2026-06-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_onboarding_step2_level_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='bulletins_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('postponed', 'Reporté'), ('partial', 'Partiel'), ('completed', 'Terminé')], db_index=True, default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='maturity_celebration_shown_for_complete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='maturity_celebration_shown_for_enriched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
