# Generated by Django 5.1.15 on 2026-06-20 00:51

import apps.students.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_bulletins_postponed_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfileHistory',
            fields=[
                ('id', models.CharField(default=apps.students.models._default_history_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('archived_reason', models.CharField(max_length=50)),
                ('previous_state', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_history', to='students.studentprofile')),
            ],
            options={
                'db_table': 'student_profile_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
