# Generated by Django 5.1.15 on 2026-09-26 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.recommendations.models_versioning


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0001_recommendation_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.recommendations.models_versioning._default_model_version_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=50, unique=True)),
                ("dataset_hash", models.CharField(max_length=80)),
                ("hyperparameters_json", models.JSONField(default=dict)),
                ("evaluation_metrics_json", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("requires_ethics_review", models.BooleanField(default=False)),
                ("ethics_review_note", models.TextField(blank=True, default="")),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("baseline_scores", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deployed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "model_versions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScoringDecision",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.recommendations.models_versioning._default_decision_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("inputs_snapshot", models.JSONField()),
                ("top_scores", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="recommendations.modelversion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "scoring_decisions",
                "ordering": ["-created_at"],
            },
        ),
    ]
