# Generated by Django 5.1.15 on 2026-08-25 15:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.family.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentInvitation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.family.models._default_invitation_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("parent_email", models.EmailField(max_length=254)),
                (
                    "relationship",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mere", "Mère"),
                            ("pere", "Père"),
                            ("tuteur", "Tuteur"),
                            ("autre", "Autre"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("custom_message", models.CharField(blank=True, max_length=200, null=True)),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("accepted", "Acceptée"),
                            ("expired", "Expirée"),
                            ("revoked", "Révoquée"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "expires_at",
                    models.DateTimeField(default=apps.family.models._default_invitation_expires_at),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_parent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["student", "status"], name="family_pare_student_c693cf_idx"
                    ),
                    models.Index(
                        fields=["parent_email", "status"], name="family_pare_parent__ba56fa_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ParentStudentLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.family.models._default_link_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mere", "Mère"),
                            ("pere", "Père"),
                            ("tuteur", "Tuteur"),
                            ("autre", "Autre"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("linked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["student", "revoked_at"], name="family_pare_student_a7a3f4_idx"
                    ),
                    models.Index(
                        fields=["parent", "revoked_at"], name="family_pare_parent__a62b63_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=("parent", "student"),
                        name="uniq_active_parent_student_link",
                    )
                ],
            },
        ),
    ]
