# Generated by Django 5.1.15 on 2026-09-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
    ]
