# Generated by Django 5.1.15 on 2026-09-26 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("parcoursup_calendar", "Calendrier Parcoursup"),
                            ("school_responses", "Réponses école"),
                            ("new_schools", "Nouvelles écoles pertinentes"),
                            ("profile_completion", "Rappels de complétion profil"),
                        ],
                        max_length=32,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_preferences",
                "constraints": [
                    models.UniqueConstraint(fields=("user", "category"), name="uniq_user_category")
                ],
            },
        ),
    ]
