# Generated by Django 5.1.15 on 2026-09-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_enable_rls"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParcoursupMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ouverture", "Ouverture Parcoursup"),
                            ("j30_fermeture_voeux", "J-30 fermeture des vœux"),
                            ("fermeture_voeux", "Fermeture des vœux"),
                            ("resultats_principale", "Résultats phase principale"),
                            ("resultats_complementaire", "Résultats phase complémentaire"),
                        ],
                        max_length=32,
                    ),
                ),
                ("campaign", models.CharField(max_length=16)),
                ("date", models.DateField()),
                ("notify_days_before", models.PositiveSmallIntegerField(default=0)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "parcoursup_milestones",
                "constraints": [
                    models.UniqueConstraint(fields=("kind", "campaign"), name="uniq_kind_campaign")
                ],
            },
        ),
    ]
