# Generated by Django 5.1.15 on 2026-09-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_parcoursupmilestone"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewSchoolsDigestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("week", models.CharField(max_length=10, unique=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("emails_queued", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "new_schools_digest_runs",
            },
        ),
    ]
