# Generated by Django 5.1.15 on 2026-09-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_pushsubscription_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='category',
            field=models.CharField(choices=[('parcoursup_calendar', 'Calendrier Parcoursup'), ('school_responses', 'Réponses école'), ('new_schools', 'Nouvelles écoles pertinentes'), ('profile_completion', 'Rappels de complétion profil'), ('report_updates', 'Suivi de tes signalements'), ('referrals', 'Parrainage')], max_length=32),
        ),
    ]
